/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./index.html",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Basic colors
        white: "#ffffff",
        black: "#000000",
        transparent: "transparent",
        
        // Brand colors
        "moveus-marigold": {
          50: "#fffbeb",
          100: "#fff2bd",
          200: "#ffea90",
          300: "#ffe162",
          400: "#ffd935",
          500: "#ddba22",
          600: "#bb9b13",
          700: "#997e08",
          800: "#776100",
          900: "#554500",
        },
        "guild-green": {
          50: "#f2fff8",
          100: "#ccffe3",
          200: "#a7ffce",
          300: "#81ffba",
          400: "#6ce2a1",
          500: "#58c589",
          600: "#47a872",
          700: "#368a5c",
          800: "#286d47",
          900: "#1b5033",
        },
        "byzantine-blue": {
          50: "#c2ceff",
          100: "#859dff",
          200: "#5c7cff",
          300: "#335cff",
          400: "#0337ff",
          500: "#002cd6",
          600: "#0024ad",
          700: "#001b85",
          800: "#00135c",
          900: "#000c3d",
        },
        "protocol-pink": {
          50: "#fff1fc",
          100: "#ffc9f3",
          200: "#ffa0eb",
          300: "#ff77e2",
          400: "#eb66cf",
          500: "#ce52b4",
          600: "#b14199",
          700: "#94317f",
          800: "#762365",
          900: "#59184b",
        },
        "oracle-orange": {
          50: "#ffefec",
          100: "#ffcdc2",
          200: "#ffab97",
          300: "#ff886d",
          400: "#FF6642",
          500: "#ea5330",
          600: "#c83e1e",
          700: "#a62c10",
          800: "#841d05",
          900: "#621300",
        },
        
        // Semantic colors
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
      },
      spacing: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        12: "48px",
        14: "56px",
        16: "64px",
        20: "80px",
        24: "96px",
        28: "112px",
        32: "128px",
        36: "144px",
        40: "160px",
        44: "176px",
        48: "192px",
        52: "208px",
        56: "224px",
        60: "240px",
        64: "256px",
        72: "288px",
        80: "320px",
        96: "384px",
        100: "400px",
        px: "1px",
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      fontSize: {
        0: "8px",
        1: "10px",
        2: "12px",
        3: "14px",
        4: "16px",
        5: "18px",
        6: "20px",
        7: "24px",
        8: "28px",
        9: "30px",
        10: "32px",
        11: "40px",
        12: "42px",
        13: "48px",
        14: "56px",
        15: "64px",
        16: "72px",
        17: "80px",
        18: "96px",
      },
      fontFamily: {
        heading: "var(--font-twk-everett)",
        body: "var(--font-neue-haas-unica-pro)",
        mono: "var(--font-twk-everett-mono)",
      },
      fontWeight: {
        hairline: "100",
        thin: "200",
        ultralight: "300",
        light: "400",
        regular: "500",
        medium: "600",
        bold: "700",
        extrabold: "800",
        super: "900",
        black: "950",
      },
      lineHeight: {
        0: "100%",
        1: "112.5%",
        2: "116.6%",
        3: "120%",
        4: "125%",
        5: "130%",
        6: "140%",
        7: "150%",
        8: "200%",
      },
      boxShadow: {
        xs: "0 0 0 1px #0000000d",
        sm: "0 1px 2px 0 #0000000d",
        DEFAULT: "0 1px 2px 0 #0000000d, 0 1px 3px 0 #0000000d",
        md: "0 2px 4px -1px #00000005, 0 4px 6px -1px #00000014",
        lg: "0 4px 6px -2px #00000005, 0 10px 15px -3px #0000000d",
        xl: "0 10px 10px -5px #00000005, 0 20px 25px -5px #0000000d",
        "2xl": "0 25px 50px -12px #00000040",
        inner: "inset 0 2px 4px 0 #00000006",
      },
      zIndex: {
        hide: "-1",
        auto: "auto",
        base: "0",
        docked: "10",
        dropdown: "1000",
        sticky: "1100",
        banner: "1200",
        overlay: "1300",
        modal: "1400",
        popover: "1500",
        skipLink: "1600",
        toast: "1700",
        tooltip: "1800",
      },
      keyframes: {
        scaleIn: {
          "0%": { transform: "scale(0)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        scaleOut: {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(0)", opacity: "0" },
        },
        dialogScaleIn: {
          "0%": { transform: "translate(-50%, -50%) scale(0.7)", opacity: "0" },
          "100%": { transform: "translate(-50%, -50%) scale(1)", opacity: "1" },
        },
        dialogScaleOut: {
          "0%": { transform: "translate(-50%, -50%) scale(1)", opacity: "1" },
          "100%": { transform: "translate(-50%, -50%) scale(0.7)", opacity: "0" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeOut: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        spin: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        slideInFromBottom: {
          "0%": { transform: "translateY(150%)" },
          "100%": { transform: "translateY(0%)" },
        },
        slideOutToBottom: {
          "0%": { transform: "translateY(0%)" },
          "100%": { transform: "translateY(150%)" },
        },
        slideInFromTop: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(0%)" },
        },
        slideOutToTop: {
          "0%": { transform: "translateY(0%)" },
          "100%": { transform: "translateY(-100%)" },
        },
        slideInFromLeft: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0%)" },
        },
        slideOutToLeft: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        slideInFromRight: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0%)" },
        },
        slideOutToRight: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(100%)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        expandHeight: {
          "0%": { height: "0px" },
          "100%": { height: "var(--height)" },
        },
        collapseHeight: {
          "0%": { height: "var(--height)" },
          "100%": { height: "0px" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        scaleIn: "scaleIn 0.2s ease-in-out",
        scaleOut: "scaleOut 0.2s ease-in-out",
        dialogScaleIn: "dialogScaleIn 0.2s ease-in-out",
        dialogScaleOut: "dialogScaleOut 0.2s ease-in-out",
        fadeIn: "fadeIn 0.2s ease-in-out",
        fadeOut: "fadeOut 0.2s ease-in-out",
        spin: "spin 1s linear infinite",
        slideInFromBottom: "slideInFromBottom 0.2s ease-in-out",
        slideOutToBottom: "slideOutToBottom 0.2s ease-in-out",
        slideInFromTop: "slideInFromTop 0.2s ease-in-out",
        slideOutToTop: "slideOutToTop 0.2s ease-in-out",
        slideInFromLeft: "slideInFromLeft 0.2s ease-in-out",
        slideOutToLeft: "slideOutToLeft 0.2s ease-in-out",
        slideInFromRight: "slideInFromRight 0.2s ease-in-out",
        slideOutToRight: "slideOutToRight 0.2s ease-in-out",
        shimmer: "shimmer 2s linear infinite",
        expandHeight: "expandHeight 0.2s ease-in-out",
        collapseHeight: "collapseHeight 0.2s ease-in-out",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};


