import { precomputeValues } from "@capsizecss/core";
import { defineTextStyles, type TextStyles, type Tokens } from "@pandacss/dev";

type FontMetrics = Parameters<typeof precomputeValues>[0]["fontMetrics"];

/** Font metrics generated by https://seek-oss.github.io/capsize/ */
const twkEverettFontMetrics = {
  capHeight: 760,
  ascent: 1010,
  descent: -211,
  lineGap: 100,
  unitsPerEm: 1000,
};

/** Font metrics generated by https://seek-oss.github.io/capsize/ */
const neueHaasUnicaProFontMetrics = {
  capHeight: 712,
  ascent: 788,
  descent: -212,
  lineGap: 200,
  unitsPerEm: 1000,
};

export const fonts = {
  heading: { value: "var(--font-twk-everett)" },
  body: { value: "var(--font-neue-haas-unica-pro)" },
  mono: { value: "var(--font-twk-everett-mono)" },
} satisfies Tokens["fonts"];

export const fontWeights = {
  hairline: { value: "100" },
  thin: { value: "200" },
  ultralight: { value: "300" },
  light: { value: "400" },
  regular: { value: "500" },
  medium: { value: "600" },
  bold: { value: "700" },
  extrabold: { value: "800" },
  super: { value: "900" },
  black: { value: "950" },
} satisfies Tokens["fontWeights"];

export const fontSizes = {
  0: { value: "8px" },
  1: { value: "10px" },
  2: { value: "12px" },
  3: { value: "14px" },
  4: { value: "16px" },
  5: { value: "18px" },
  6: { value: "20px" },
  7: { value: "24px" },
  8: { value: "28px" },
  9: { value: "30px" },
  10: { value: "32px" },
  11: { value: "40px" },
  12: { value: "42px" },
  13: { value: "48px" },
  14: { value: "56px" },
  15: { value: "64px" },
  16: { value: "72px" },
  17: { value: "80px" },
  18: { value: "96px" },
} satisfies Tokens["fontSizes"];

export const lineHeights = {
  0: { value: "100%" },
  1: { value: "112.5%" },
  2: { value: "116.6%" },
  3: { value: "120%" },
  4: { value: "125%" },
  5: { value: "130%" },
  6: { value: "140%" },
  7: { value: "150%" },
  8: { value: "200%" },
} satisfies Tokens["lineHeights"];

export const fontStyle = {
  normal: { value: "normal" },
  italic: { value: "italic" },
};

export const letterSpacing = {
  0: { value: "0%" },
  1: { value: "10%" },
  56: { value: "56%" },
  58: { value: "58%" },
};

export const paragraphSpacing = {
  0: { value: "0" },
};

export const textCase = {
  none: { value: "none" },
  uppercase: { value: "uppercase" },
};

export const textDecoration = {
  none: { value: "none" },
};

export const paragraphIndent = {
  0: { value: "0px" },
};

interface Recursive<T> {
  [key: string]: Recursive<T> | T;
}
type ExtractRecursive<T> = T extends Recursive<infer X> ? X : never;

interface Token<T> {
  value: T;
  description?: string;
}
type ExtractToken<T> = T extends Token<infer X> ? X : never;

type TextStyle = ExtractToken<ExtractRecursive<TextStyles>>;

interface CreateTextStyleArgs {
  fontSize: keyof typeof fontSizes;
  lineHeight: keyof typeof lineHeights;
}

const createTextVariant = (
  baseTextStyle: TextStyle,
  fontMetrics: FontMetrics
) => {
  const createTextStyle = ({ fontSize, lineHeight }: CreateTextStyleArgs) => {
    return {
      value: {
        ...baseTextStyle,
        fontVariationSettings: '"slnt" 0',
        fontSize: fontSizes[fontSize].value,
        lineHeight: lineHeights[lineHeight].value,
      },
    };
  };
  createTextStyle.capsize = ({ fontSize, lineHeight }: CreateTextStyleArgs) => {
    const capsizeValues = precomputeValues({
      fontSize: parseInt(fontSize.toString()),
      leading: parseInt(lineHeight.toString()),
      fontMetrics,
    });

    return {
      value: {
        ...baseTextStyle,
        fontVariationSettings: '"slnt" 0',
        fontSize: capsizeValues.fontSize,
        lineHeight: capsizeValues.lineHeight,
        _before: {
          content: '""',
          marginBottom: capsizeValues.capHeightTrim,
          display: "table",
        },
        _after: {
          content: '""',
          marginTop: capsizeValues.baselineTrim,
          display: "table",
        },
      },
    };
  };

  return createTextStyle;
};

// Heading styles with TWK Everett
const createHeadingLargeStyle = createTextVariant(
  {
    fontFamily: fonts.heading.value,
    fontWeight: fontWeights.bold.value,
  },
  twkEverettFontMetrics
);

const createHeadingSmallStyle = createTextVariant(
  {
    fontFamily: fonts.heading.value,
    fontWeight: fontWeights.bold.value,
  },
  twkEverettFontMetrics
);

// TWK Everett Mono styles
const createMonoBoldStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.bold.value,
  },
  twkEverettFontMetrics
);

const createMonoMediumStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.medium.value,
  },
  twkEverettFontMetrics
);

const createMonoRegularStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.regular.value,
  },
  twkEverettFontMetrics
);

const createMonoLightStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.light.value,
  },
  twkEverettFontMetrics
);

const createMonoHairlineStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.hairline.value,
  },
  twkEverettFontMetrics
);

const createMonoThinStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.thin.value,
  },
  twkEverettFontMetrics
);

const createMonoUltralightStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.ultralight.value,
  },
  twkEverettFontMetrics
);

const createMonoExtraboldStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.extrabold.value,
  },
  twkEverettFontMetrics
);

const createMonoSuperStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.super.value,
  },
  twkEverettFontMetrics
);

const createMonoBlackStyle = createTextVariant(
  {
    fontFamily: fonts.mono.value,
    fontWeight: fontWeights.black.value,
  },
  twkEverettFontMetrics
);

// Body styles with Neue Haas Unica Pro
const createBodyHeavyStyle = createTextVariant(
  {
    fontFamily: fonts.body.value,
    fontWeight: fontWeights.black.value,
  },
  neueHaasUnicaProFontMetrics
);

const createBodyBoldStyle = createTextVariant(
  {
    fontFamily: fonts.body.value,
    fontWeight: fontWeights.bold.value,
  },
  neueHaasUnicaProFontMetrics
);

const createBodyMediumStyle = createTextVariant(
  {
    fontFamily: fonts.body.value,
    fontWeight: fontWeights.medium.value,
  },
  neueHaasUnicaProFontMetrics
);

const createBodyLightStyle = createTextVariant(
  {
    fontFamily: fonts.body.value,
    fontWeight: fontWeights.light.value,
  },
  neueHaasUnicaProFontMetrics
);

// Tables/uppercase style
const createTablesStyle = createTextVariant(
  {
    fontFamily: fonts.body.value,
    fontWeight: fontWeights.regular.value,
    textTransform: "uppercase",
  },
  neueHaasUnicaProFontMetrics
);

export const textStyles = defineTextStyles({
  // Heading styles
  "heading-large": {
    xs: createHeadingLargeStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    sm: createHeadingLargeStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    md: createHeadingLargeStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
    lg: createHeadingLargeStyle({ fontSize: 7, lineHeight: 0 }), // 24px, 100%
    xl: createHeadingLargeStyle({ fontSize: 8, lineHeight: 0 }), // 28px, 100%
    "2xl": createHeadingLargeStyle({ fontSize: 9, lineHeight: 0 }), // 30px, 100%
    "3xl": createHeadingLargeStyle({ fontSize: 10, lineHeight: 0 }), // 32px, 100%
    "4xl": createHeadingLargeStyle({ fontSize: 11, lineHeight: 0 }), // 40px, 100%
    "5xl": createHeadingLargeStyle({ fontSize: 13, lineHeight: 0 }), // 48px, 100%
  },
  "heading-small": {
    xs: createHeadingSmallStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createHeadingSmallStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createHeadingSmallStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createHeadingSmallStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createHeadingSmallStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },

  // TWK Everett Mono styles
  "mono-bold": {
    xs: createMonoBoldStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoBoldStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoBoldStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoBoldStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoBoldStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-medium": {
    xs: createMonoMediumStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoMediumStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoMediumStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoMediumStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoMediumStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-regular": {
    xs: createMonoRegularStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoRegularStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoRegularStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoRegularStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoRegularStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-light": {
    xs: createMonoLightStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoLightStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoLightStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoLightStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoLightStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-hairline": {
    xs: createMonoHairlineStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoHairlineStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoHairlineStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoHairlineStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoHairlineStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-thin": {
    xs: createMonoThinStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoThinStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoThinStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoThinStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoThinStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-ultralight": {
    xs: createMonoUltralightStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoUltralightStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoUltralightStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoUltralightStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoUltralightStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-extrabold": {
    xs: createMonoExtraboldStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoExtraboldStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoExtraboldStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoExtraboldStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoExtraboldStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-super": {
    xs: createMonoSuperStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoSuperStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoSuperStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoSuperStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoSuperStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "mono-black": {
    xs: createMonoBlackStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createMonoBlackStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createMonoBlackStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createMonoBlackStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createMonoBlackStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },

  // Body styles with Neue Haas Unica Pro
  "body-heavy": {
    xs: createBodyHeavyStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createBodyHeavyStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createBodyHeavyStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createBodyHeavyStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createBodyHeavyStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "body-bold": {
    xs: createBodyBoldStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createBodyBoldStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createBodyBoldStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createBodyBoldStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createBodyBoldStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "body-medium": {
    xs: createBodyMediumStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createBodyMediumStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createBodyMediumStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createBodyMediumStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createBodyMediumStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "body-light": {
    xs: createBodyLightStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createBodyLightStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createBodyLightStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createBodyLightStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createBodyLightStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
  "body-regular": {
    xs: createTextVariant(
      {
        fontFamily: fonts.body.value,
        fontWeight: fontWeights.regular.value,
      },
      neueHaasUnicaProFontMetrics
    )({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createTextVariant(
      {
        fontFamily: fonts.body.value,
        fontWeight: fontWeights.regular.value,
      },
      neueHaasUnicaProFontMetrics
    )({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createTextVariant(
      {
        fontFamily: fonts.body.value,
        fontWeight: fontWeights.regular.value,
      },
      neueHaasUnicaProFontMetrics
    )({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createTextVariant(
      {
        fontFamily: fonts.body.value,
        fontWeight: fontWeights.regular.value,
      },
      neueHaasUnicaProFontMetrics
    )({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createTextVariant(
      {
        fontFamily: fonts.body.value,
        fontWeight: fontWeights.regular.value,
      },
      neueHaasUnicaProFontMetrics
    )({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },

  // Tables/uppercase
  "tables-uppercase": {
    xs: createTablesStyle({ fontSize: 2, lineHeight: 0 }), // 12px, 100%
    sm: createTablesStyle({ fontSize: 3, lineHeight: 0 }), // 14px, 100%
    md: createTablesStyle({ fontSize: 4, lineHeight: 0 }), // 16px, 100%
    lg: createTablesStyle({ fontSize: 5, lineHeight: 0 }), // 18px, 100%
    xl: createTablesStyle({ fontSize: 6, lineHeight: 0 }), // 20px, 100%
  },
});
